name: Payment CI test for submodule check

on:
  push:
    paths:
      - 'services/payment/**'
      - '.github/workflows/payment-test-build.yml'
    branches:
      - 'main'
    tags:
      - '*'  # 모든 태그 푸시 시 실행

jobs:
  check_submodule_version:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: true  # 서브모듈까지 포함하여 체크아웃

      - name: Save current submodule versions (local)
        id: save_local
        run: |
          echo "Saving current submodule versions (local)..."
          LOCAL_STATUS=$(git submodule status)
          echo "Local submodule status:"
          echo "$LOCAL_STATUS"
          echo "::set-output name=local_status::$LOCAL_STATUS"
      - name: Update submodules to latest version
        run: |
          echo "Updating submodules to the latest remote version..."
          git submodule update --remote

      - name: Save updated submodule versions (remote)
        id: save_remote
        run: |
          echo "Saving updated submodule versions (remote)..."
          REMOTE_STATUS=$(git submodule status)
          echo "Remote submodule status:"
          echo "$REMOTE_STATUS"
          echo "::set-output name=remote_status::$REMOTE_STATUS"

      - name: Compare submodule versions
        run: |
          echo "Comparing local and remote submodule versions..."
          if [ "${{ steps.save_local.outputs.local_status }}" = "${{ steps.save_remote.outputs.remote_status }}" ]; then
            echo "Submodules are up to date."
          else
            echo "Submodule version mismatch detected!"
            echo "Local submodule status:"
            echo "${{ steps.save_local.outputs.local_status }}"
            echo "Remote submodule status:"
            echo "${{ steps.save_remote.outputs.remote_status }}"
            exit 1
          fi