name: User CI test for submodule check

on:
  push:
    paths:
      - 'services/user/**'
      - '.github/workflows/user-test-build.yml'
    branches:
      - 'main'
    tags:
      - '*'  # 모든 태그 푸시 시 실행

jobs:
  check_submodule_version:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: true  # 서브모듈까지 포함하여 체크아웃

      - name: Update submodules to latest version
        run: git submodule update --remote

      - name: Check for submodule changes in all microservices
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "Submodule version mismatch detected!"
            exit 1
          else
            echo "All submodules are up to date."
          fi
